name: tidb-ai-integration-test

services:
  tidb:
    image: wangdi4zm/tind:v7.5.3-vector-index
    restart: always
    volumes:
      - ${E2E_DATA_TIDB_DIR:-.data/tidb}:/app/data

  redis:
    image: redis:6.0.16
    restart: always
    volumes:
      - ${E2E_DATA_REDIS_DIR:-.data/redis}:/data

  backend:
    image: tidbai/backend:${E2E_DOCKER_TAG_BACKEND}
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:80"
    env_file:
      - .env.backend
    volumes:
      - ${E2E_DATA_STORAGE_DIR:-.data/storage}:/shared/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  frontend:
    image: tidbai/frontend:${E2E_DOCKER_TAG_FRONTEND}
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://backend
    env_file:
      - .env.frontend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  background:
    image: tidbai/backend:${E2E_DOCKER_TAG_BACKEND}
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env.backend
    command: /usr/bin/supervisord
    volumes:
      - ${E2E_DATA_STORAGE_DIR:-.data/storage}:/shared/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  static-web-server:
    image: joseluisq/static-web-server:2
    restart: always
    ports:
      - "4001:80"
    volumes:
      - ./test-html:/public

  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password

  langfuse:
    image: langfuse/langfuse:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5001:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
      NEXTAUTH_URL: http://localhost:5001
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
      ENCRYPTION_KEY: 29da5e11c513945cabadefd32a3802f6c432e2ff2fa8bfae168ca8e4c7fb55d3
      LANGFUSE_INIT_USER_EMAIL: langfuse@tidb.ai
      LANGFUSE_INIT_USER_NAME: TiDB.AI
      LANGFUSE_INIT_USER_PASSWORD: password
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: lf_pk_1234567890
      LANGFUSE_INIT_PROJECT_SECRET_KEY: lf_sk_1234567890
      LANGFUSE_INIT_PROJECT_NAME: tidb.ai
      LANGFUSE_INIT_PROJECT_ID: tidb-ai
      LANGFUSE_INIT_ORG_NAME: PingCAP
      LANGFUSE_INIT_ORG_ID: pingcap
